Feature/equip equipment
david-buderus/PP-Manager pull request #44
Opened 2021-10-25 12:31 UTC by david-buderus

Added support so that a client can equip items from his inventory

2021-10-25 19:51 UTC, bastihav requested changes

2021-10-25 19:51 UTC, bastihav commented on server/src/main/java/de/pnp/manager/main/Utility.java
> +        amountPerType.put(null, config.getInt("character.jewellery.amount.other"));
we should really not use null as a key

2021-10-26 08:29 UTC, david-buderus commented on server/src/main/java/de/pnp/manager/main/Utility.java
> +        amountPerType.put(null, config.getInt("character.jewellery.amount.other"));
Then I need a key that a user can not use.
Or another way to realise a fallback value.

2021-12-15 08:45 UTC, bastihav approved these changes

2021-12-17 21:44 UTC, merged